#!/bin/bash
#	xbmll.cn 出品
mv /home/onyd/index.php /home/wwwroot/default/dnsml/ >/dev/null 2>&1
mv /home/onyd/meteor.php /home/wwwroot/default/dnsml/ >/dev/null 2>&1
sleep 1
echo -e "\033[34m开启云端访问成功\033[0m"